requires 'DBI';
requires 'DBD::mysql';
requires 'JSON';
requires 'Spreadsheet::ParseXLSX';

test_requires 'Test::Warnings';
test_requires 'Test::Differences';
test_requires 'Test::Exception', '>0.42';
test_requires 'Test::MockObject';
test_requires 'Test::Deep';
test_requires 'Test::More';
test_requires 'Devel::Peek';
test_requires 'Devel::Cycle';
test_requires 'Error';
test_requires 'PadWalker';
test_requires 'Test::Builder::Module';
test_requires 'IO::String';
test_requires 'Test::Perl::Critic';
test_requires 'Test::Pod::Coverage';
test_requires 'Perl::Critic::Utils';
